"""empty message

Revision ID: 00827e99c890
Revises: 062268b0bf23
Create Date: 2026-01-09 16:36:45.722785

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00827e99c890'
down_revision = '062268b0bf23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('code',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=20),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=sa.String(length=20),
               type_=mysql.FLOAT(),
               existing_nullable=False)
        batch_op.alter_column('month',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
