"""empty message

Revision ID: 062268b0bf23
Revises: 
Create Date: 2026-01-09 16:28:58.099590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '062268b0bf23'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcash_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('transaction_date', sa.String(length=10), nullable=True),
    sa.Column('code', sa.Float(), nullable=False),
    sa.Column('received_amount', sa.Float(), nullable=False),
    sa.Column('posted', sa.Boolean(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('Memberid', sa.String(length=8), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_column('Memberid')
        batch_op.drop_column('member_name')

    op.drop_table('mcash_records')
    # ### end Alembic commands ###
