"""empty message

Revision ID: 0cfa5423ed3a
Revises: bb17b1a27983
Create Date: 2026-01-05 19:08:03.871883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cfa5423ed3a'
down_revision = 'bb17b1a27983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
