"""add otp fields to user

Revision ID: 12750f4df1d9
Revises: d8f11bd8948a
Create Date: 2026-03-17 21:11:18.960815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12750f4df1d9'
down_revision = 'd8f11bd8948a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repayment_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=50), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('principal', sa.Float(), nullable=True),
    sa.Column('interest', sa.Float(), nullable=True),
    sa.Column('total_payment', sa.Float(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repayment_schedule')
    # ### end Alembic commands ###
