"""empty message

Revision ID: 163a18677cd8
Revises: 676e1136e709
Create Date: 2026-01-04 21:03:33.696928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163a18677cd8'
down_revision = '676e1136e709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=8), nullable=False),
    sa.Column('memberName', sa.String(length=100), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contribution')
    # ### end Alembic commands ###
