"""product factory

Revision ID: 2712df15f709
Revises: 6c8092ee0f89
Create Date: 2026-05-08 11:00:59.955235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2712df15f709'
down_revision = '6c8092ee0f89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_completed_step', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('last_completed_step')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
