"""empty message

Revision ID: 2c9b8bd54471
Revises: ca9fe0191e56
Create Date: 2026-01-04 16:58:18.273580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9b8bd54471'
down_revision = 'ca9fe0191e56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chama_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Float(), nullable=False),
    sa.Column('registration_fee', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('Weekly', 'Monthly', 'Yearly', name='frequencyenum'), nullable=False),
    sa.Column('cut_off_day', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Enum('Savings', 'Credit', 'Both', name='organizationtypeenum'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('credit_multiplier', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chama_settings')
    # ### end Alembic commands ###
