"""empty message

Revision ID: 45578667aa7a
Revises: 00827e99c890
Create Date: 2026-01-09 16:39:37.848889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45578667aa7a'
down_revision = '00827e99c890'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.alter_column('month',
               existing_type=sa.DATE(),
               type_=sa.String(length=7),
               nullable=True)
        batch_op.alter_column('transaction_date',
               existing_type=sa.DATE(),
               type_=sa.String(length=10),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.alter_column('transaction_date',
               existing_type=sa.String(length=10),
               type_=sa.DATE(),
               existing_nullable=True)
        batch_op.alter_column('month',
               existing_type=sa.String(length=7),
               type_=sa.DATE(),
               nullable=False)

    # ### end Alembic commands ###
