"""add audit_logs table

Revision ID: 5122f7d23551
Revises: 9b4e607c0627
Create Date: 2026-04-11 14:52:18.905599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5122f7d23551'
down_revision = '9b4e607c0627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('changes', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('snapshot', sa.JSON(), nullable=True))
        batch_op.drop_column('new_value')
        batch_op.drop_column('old_value')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('old_value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('new_value', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('snapshot')
        batch_op.drop_column('changes')

    # ### end Alembic commands ###
