"""initial clean schema12

Revision ID: 537b4f5e9f9d
Revises: 
Create Date: 2026-03-29 17:33:26.886749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '537b4f5e9f9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['id'])

    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('amount', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key(None, 'credit', ['loan_id'], ['loan_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('amount')
        batch_op.drop_column('loan_id')

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('member_id')

    # ### end Alembic commands ###
