"""product factory

Revision ID: 56aa06537774
Revises: 72d47aa33ec7
Create Date: 2026-05-10 12:59:58.985933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56aa06537774'
down_revision = '72d47aa33ec7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_paid', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.drop_column('registration_paid')

    # ### end Alembic commands ###
