"""product factory

Revision ID: 72d47aa33ec7
Revises: 9332bd023c40
Create Date: 2026-05-10 12:57:13.863369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72d47aa33ec7'
down_revision = '9332bd023c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_product', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contribution', schema=None) as batch_op:
        batch_op.drop_column('savings_product')

    # ### end Alembic commands ###
