"""empty message

Revision ID: 74641b630f17
Revises: 163a18677cd8
Create Date: 2026-01-04 21:37:42.622219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74641b630f17'
down_revision = '163a18677cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=False),
    sa.Column('member_id', sa.String(length=8), nullable=False),
    sa.Column('amount_requested', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('Active', 'Completed', 'Defaulted', name='creditstatusenum'), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit')
    # ### end Alembic commands ###
