"""Credit y

Revision ID: 8199b6d65550
Revises: 8ca711cc8718
Create Date: 2026-03-29 10:53:47.318271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8199b6d65550'
down_revision = '8ca711cc8718'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_loansinterest_buffer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=50), nullable=True),
    sa.Column('interest_date', sa.Date(), nullable=True),
    sa.Column('product_type', sa.String(length=100), nullable=True),
    sa.Column('interest_amount', sa.Float(), nullable=True),
    sa.Column('outstanding_balance', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_loansinterest_buffer')
    # ### end Alembic commands ###
