"""Credit y

Revision ID: 82c2463b8523
Revises: 
Create Date: 2026-04-05 11:01:31.496385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c2463b8523'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collateral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['credit.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guarantor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=True),
    sa.Column('member_number', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('amount_guaranteed', sa.Float(), nullable=True),
    sa.Column('total_shares', sa.Float(), nullable=True),
    sa.Column('committed_amount', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['credit.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['member_id'])

    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'member', ['member_id'], ['member_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('beneficiary', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    op.drop_table('guarantor')
    op.drop_table('collateral')
    # ### end Alembic commands ###
