"""empty message

Revision ID: 84c294532c38
Revises: 45578667aa7a
Create Date: 2026-01-09 23:05:46.439762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84c294532c38'
down_revision = '45578667aa7a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loanno', sa.String(length=20), nullable=True))

    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loanno', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mpesa_transactions', schema=None) as batch_op:
        batch_op.drop_column('loanno')

    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.drop_column('loanno')

    # ### end Alembic commands ###
