"""product factory

Revision ID: 9332bd023c40
Revises: 2712df15f709
Create Date: 2026-05-10 11:36:10.784134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9332bd023c40'
down_revision = '2712df15f709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registration_acc', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chama_settings', schema=None) as batch_op:
        batch_op.drop_column('registration_acc')

    # ### end Alembic commands ###
