"""empty message

Revision ID: 934a3536ae54
Revises: 0cfa5423ed3a
Create Date: 2026-01-05 21:02:26.619672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '934a3536ae54'
down_revision = '0cfa5423ed3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credit_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('remaining_balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['loan_id'], ['credit.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('schedule_generated', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_column('schedule_generated')

    op.drop_table('credit_repayments')
    # ### end Alembic commands ###
