"""empty message

Revision ID: a5855a7542c0
Revises: 84c294532c38
Create Date: 2026-01-09 23:39:41.890938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5855a7542c0'
down_revision = '84c294532c38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('installment', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mcash_records', schema=None) as batch_op:
        batch_op.drop_column('installment')

    # ### end Alembic commands ###
