"""empty message

Revision ID: bb17b1a27983
Revises: da62714b56be
Create Date: 2026-01-05 18:48:16.579870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb17b1a27983'
down_revision = 'da62714b56be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('amount_paid',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.alter_column('amount_paid',
               existing_type=mysql.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###
