"""empty message

Revision ID: ced311b0d8f7
Revises: 934a3536ae54
Create Date: 2026-01-06 11:51:37.819363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced311b0d8f7'
down_revision = '934a3536ae54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_repayments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit_repayments', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
