"""empty message

Revision ID: da62714b56be
Revises: 74641b630f17
Create Date: 2026-01-05 16:00:55.559635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da62714b56be'
down_revision = '74641b630f17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credit', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
