"""empty message

Revision ID: e2aee7b61599
Revises: 
Create Date: 2026-02-08 17:00:50.611767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2aee7b61599'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chama_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contribution_amount', sa.Float(), nullable=False),
    sa.Column('registration_fee', sa.Float(), nullable=False),
    sa.Column('frequency', sa.Enum('Weekly', 'Monthly', 'Yearly', name='frequencyenum'), nullable=False),
    sa.Column('cut_off_day', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Enum('Savings', 'Credit', 'Both', name='organizationtypeenum'), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), nullable=True),
    sa.Column('notification_date', sa.Date(), nullable=True),
    sa.Column('credit_multiplier', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('installments', sa.Integer(), nullable=True),
    sa.Column('penalty_rate', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member',
    sa.Column('id', sa.String(length=8), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('amountPaid', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=True),
    sa.Column('registrationPaid', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mpesa_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('receipt', sa.String(length=50), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=False),
    sa.Column('checkout_request_id', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('trans_time', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'success', 'failed', name='mpesa_status'), nullable=True),
    sa.Column('transaction_type', sa.Enum('registration_fee', 'shares_contribution', 'penalty_due', 'loan_repayment', name='transaction_type'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('checkout_request_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('default_monthly_amount', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_id')
    )
    op.create_table('contribution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('memberId', sa.String(length=8), nullable=False),
    sa.Column('memberName', sa.String(length=100), nullable=True),
    sa.Column('month', sa.String(length=7), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['memberId'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=False),
    sa.Column('member_id', sa.String(length=8), nullable=False),
    sa.Column('amount_requested', sa.Integer(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('installments', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('schedule_generated', sa.Boolean(), nullable=True),
    sa.Column('paid_interest', sa.Float(), nullable=True),
    sa.Column('interest_method', sa.String(length=50), nullable=True),
    sa.Column('paid_penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('Pending', 'Active', 'Completed', 'Defaulted', name='creditstatusenum'), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('loan_id')
    )
    op.create_table('vendor_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('month', sa.Date(), nullable=False),
    sa.Column('expected_amount', sa.Float(), nullable=False),
    sa.Column('amount_received', sa.Float(), nullable=False),
    sa.Column('outstanding_amount', sa.Float(), nullable=False),
    sa.Column('received_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_repayments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.String(length=10), nullable=False),
    sa.Column('installment_number', sa.Integer(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('interest', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=False),
    sa.Column('remaining_balance', sa.Float(), nullable=False),
    sa.Column('interest_paid', sa.Float(), nullable=True),
    sa.Column('principal_paid', sa.Float(), nullable=True),
    sa.Column('penalty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penalty_paid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('penalty_applied_at', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['loan_id'], ['credit.loan_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('credit_repayments')
    op.drop_table('vendor_ledger')
    op.drop_table('credit')
    op.drop_table('contribution')
    op.drop_table('vendors')
    op.drop_table('user')
    op.drop_table('mpesa_transactions')
    op.drop_table('member')
    op.drop_table('chama_settings')
    # ### end Alembic commands ###
