"""Accounts

Revision ID: f0b92b8b0fdb
Revises: f3f34e0d433f
Create Date: 2026-04-11 13:11:37.558197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0b92b8b0fdb'
down_revision = 'f3f34e0d433f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_postable', sa.Boolean(), nullable=True))
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
        batch_op.create_unique_constraint(None, ['code'])
        batch_op.create_foreign_key(None, 'account', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('code',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
        batch_op.drop_column('is_postable')
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
